### ISSUE TITLE
Item Frame Error

### ISSUE THREAD

**Issue by AlexPads** [AndreasHGK/BankNotes#4]
When you put a banknote in an item Frame when you take it out you still have the banknote so you can infinetly deposit it !!

**Comment by andreashgk** [comment]
This is something you are only able to do on creative, idk why you need a patch for it but i did it anyway. Didn't test it yet because PMMP is out of date. Just grab dev7 from poggit and it should work.

**Comment by AlexPads** [comment]
we were doing it in Survival But THANKS!!!!

**Comment by AlexPads** [comment]
SOrry to say But im using Dev-7 and the error Still occurs :(

https://youtu.be/gnGsrnFId5M This is a Link to a vid of me on my server showing the error.
