### ISSUE TITLE
Item frame error. 

### ISSUE THREAD

**Issue by AlexPads** [AndreasHGK/BankNotes#5]
i was not sure if i needed to open a new error so i did sorry to bother you.

https://youtu.be/gnGsrnFId5M Here is a link to me on my server showing the error. hope this helps :)

-Pocketmine 3.2.0
-Php 7.2
-banknotedev-7.phar
- TinyPixel.us.to (server)

**Comment by andreashgk** [comment]
oh! now i get it ok sorry i will see what i can do to fix it

**Comment by andreashgk** [comment]
Finally fixed. Banknote collection won't work on these blocks:
(so you don't accidently collect it while eg. opening a chest)

 - Item Frame
 - Anvil
 - Crafting Table
 - Furnace
 - Chest
 - Brewing Stand
 - Cake
 - Wooden Door
 - Wooden Button
 - Stone Button
 - Enchanting Table
 - Ender Chest
 - Fence Gate
 - Iron Door
 - Stonecutter
 - Trapped Chest
 - Wooden Trapdoor
 - Bed

Thank you for posting the issue and don't worry it didn't bother me

**Comment by andreashgk** [comment]
the fix, together with some additions has been submitted, but a newer version is already in the works.

**Comment by AlexPads** [comment]
Thanks love this plugin!

**Comment by andreashgk** [comment]
No problem!
